coverage:
  status:
    project:
      default:
        target: auto
      mypy:
        target: auto
        flags:
          - mypy

      tests:
        target: auto
        flags:
          - tests
